isaacsim.replicator.caption.core:
  version: 0.0.9
  camera_prim_path: /World/G1/torso_link/d435_camera
  scene_path: ''
  caption_configs:
    save_full_scene_graph: true
    save_pruned_scene_graph: true
    attach_label_to_usd: false
    use_ai_label: false
    visualize_caption: true
    max_object_capacity: 100
    export_edges: true
    global_caption: false
    qa_caption: false
    brief_caption: true
    pruning_ratio: 1.0
    verbose: true
    random_seed: 0
    caption_only: true
    export_world: true
  output_path: /home/thakk100/Projects/thesis/G1_sim/docs/screenshots/envs_20260924/tabletop_wheel/caption
